import { Routes } from '@angular/router';
import {HomeComponent} from "./components/home/home.component";
import {PageNotFoundComponent} from "./components/page-not-found/page-not-found.component";

export const routes: Routes = [
  { path: 'welcome', component: HomeComponent  },
  /*
  { path: 'auth', component: LoginComponent  },
  { path: 'login', component: LoginComponent  },
  { path: 'profile', component: ProfileComponent, canActivate: [authGuard]   },
  { path: 'register', component: RegisterComponent  },
  { path: 'navigation-main', component: NavigationMainComponent, canActivate: [authGuard]   },
  { path: 'navigation-configuration', component: NavigationConfigurationComponent , canActivate: [adminGuard]},
  { path: 'navigation-configuration-panel', component: NavigationConfigPanelComponent , canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert', component: AlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert/list', component: ListAlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert/add', component: AddAlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert/detail', component: DetailAlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert/edit', component: EditAlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/alert/delete', component: DeleteAlertComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/label', component: LabelComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image', component: ImageComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image/list', component: ImageListComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image/add', component: ImageAddComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image/detail', component: ImageDetailComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image/edit', component: ImageEditComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/image/delete', component: ImageDeleteComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text', component: FreeTextComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text/list', component: FreeTextListComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text/add', component: FreeTextAddComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text/detail', component: FreeTextDetailComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text/edit', component: FreeTextEditComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/free-text/delete', component: FreeTextDeleteComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component', component: ComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component/list', component: ListComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component/add', component: AddComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component/detail', component: DetailComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component/edit', component: EditComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/component/delete', component: DeleteComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel', component: PanelComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel/list', component: PanelListComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel/add', component: PanelAddComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel/detail', component: PanelDetailComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel/edit', component: PanelEditComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/panel/delete', component: PanelDeleteComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component', component: NavigationComponentComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component/list', component: NavigationComponentListComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component/add', component: NavigationComponentAddComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component/detail', component: NavigationComponentDetailComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component/edit', component: NavigationComponentEditComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-component/delete', component: NavigationComponentDeleteComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process', component: NavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process/list', component: ListNavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process/add', component: AddNavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process/detail', component: DetailNavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process/edit', component: EditNavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-configuration/navigation-process/delete', component: DeleteNavigationProcessComponent, canActivate: [adminGuard]},
  { path: 'navigation-business-domain', component: NavigationBusinessDomainComponent, canActivate: [userGuard]   },
  { path: 'navigation-business-domain/rationale', component: RationaleComponent, canActivate: [userGuard]   },
  { path: 'navigation-application-board', component: NavigationApplicationBoardComponent, canActivate: [userGuard]   },
  { path: 'navigation-roadmap', component: NavigationRoadmapComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance', component: NavigationQualityAssuranceComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/qa-rationale', component: QaRationaleComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/action-verb', component: ActionVerbComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/glossary', component: GlossaryComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/glossary/list', component: ListGlossaryComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/glossary/add', component: AddGlossaryComponent, canActivate: [moderatorGuard]   },
  { path: 'navigation-quality-assurance/glossary/edit', component: EditGlossaryComponent, canActivate: [moderatorGuard]   },
  { path: 'navigation-quality-assurance/glossary/detail', component: DetailGlossaryComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-assurance/glossary/delete', component: DeleteGlossaryComponent, canActivate: [moderatorGuard]   },
  { path: 'navigation-quality-assurance/glossary/export', component: ExportGlossaryComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework', component: NavigationStakeholderFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder', component: StakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder/list', component: ListStakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder/edit', component: EditStakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder/add', component: AddStakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder/delete', component: DeleteStakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/stakeholder/detail', component: DetailStakeholderComponent, canActivate: [userGuard]   },
  { path: 'navigation-stakeholder-framework/role', component: RoleComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework', component: NavigationWorkProductFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance', component: ApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance/list', component: ListApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance/add', component: AddApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance/edit', component: EditApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance/delete', component: DeleteApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/appliance/detail', component: DetailApplianceComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic', component: GenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic/add', component: AddGenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic/edit', component: EditGenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic/list', component: ListGenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic/delete', component: DeleteGenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-work-product-framework/generic/detail', component: DetailGenericComponent, canActivate: [userGuard]   },
  { path: 'navigation-testing-framework', component: NavigationTestingFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-project-framework', component: NavigationProjectFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework', component: NavigationProcessFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework-panel', component: NavigationProcessFrameworkPanelComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework/process-category', component: ProcessCategoriesComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework/process', component: ProcessComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework/activity', component: ActivityComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework/task', component: TaskComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework', component: NavigationProcessFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-process-framework', component: NavigationProcessFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework', component: NavigationLifecycleFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework/cycle', component: LifecycleComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework/phase', component: LifecyclePhaseComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework/entry', component: LifecycleEntryCriteriaComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework/exit', component: LifecycleExitCriteriaComponent, canActivate: [userGuard]   },
  { path: 'navigation-lifecycle-framework/goal', component: LifecycleGoalComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework', component: NavigationQualityFrameworkComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-category', component: QualityCategoryComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-requirement', component: QualityRequirementComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-attribute', component: QualityAttributeComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-characteristic', component: QualityCharacteristicComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-sub-characteristic', component: QualitySubCharacteristicComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-measure-element', component: QualityMeasureElementComponent, canActivate: [userGuard]   },
  { path: 'navigation-quality-framework/quality-metric', component: QualityMetricComponent, canActivate: [userGuard]   },
*/
  { path: '',   redirectTo: '/welcome', pathMatch: 'full' },
  { path: '**', component: PageNotFoundComponent }
];
